// Emoji.json 
{ 
	"Happy": [ 
		{ "emoji": "????", "name": "Grinning Face" }, 
		{ "emoji": "????", "name": "Beaming Face with Smiling Eyes" }, 
		{ "emoji": "????", "name": "Smiling Face with Open Mouth and Smiling Eyes" }, 
		{ "emoji": "????", "name": "Grinning Face with Big Eyes" }, 
		{ "emoji": "????", "name": "Grinning Squinting Face" }, 
		{ "emoji": "????", "name": "Grinning Face with Sweat" }, 
		{ "emoji": "????", "name": "Slightly Smiling Face" }, 
		{ "emoji": "????", "name": "Smiling Face with Smiling Eyes" }, 
		{ "emoji": "????", "name": "Smiling Face with Halo" }, 
		{ "emoji": "????", "name": "Smiling Face with Hearts" }, 
		{ "emoji": "????", "name": "Heart Eyes" }, 
		{ "emoji": "????", "name": "Star-Struck" }, 
		{ "emoji": "????", "name": "Face Blowing a Kiss" }, 
		{ "emoji": "????", "name": "Kissing Face" }, 
		{ "emoji": "????", "name": "Kissing Face with Smiling Eyes" }, 
		{ "emoji": "????", "name": "Face Savoring Food" }, 
		{ "emoji": "????", "name": "Face with Tongue" }, 
		{ "emoji": "????", "name": "Winking Face with Tongue" }, 
		{ "emoji": "????", "name": "Partying Face" }, 
		{ "emoji": "????", "name": "Grinning Cat Face" } 
	], 
		"Sad": [ 
			{ "emoji": "????", "name": "Disappointed Face" }, 
			{ "emoji": "????", "name": "Pensive Face" }, 
			{ "emoji": "????", "name": "Crying Face" }, 
			{ "emoji": "????", "name": "Loudly Crying Face" }, 
			{ "emoji": "????", "name": "Weary Face" }, 
			{ "emoji": "????", "name": "Tired Face" }, 
			{ "emoji": "????", "name": "Suffering Face" }, 
			{ "emoji": "????", "name": "Confounded Face" }, 
			{ "emoji": "????", "name": "Anxious Face with Sweat" }, 
			{ "emoji": "????", "name": "Fearful Face" }, 
			{ "emoji": "????", "name": "Downcast Face with Sweat" }, 
			{ "emoji": "????", "name": "Sad but Relieved Face" }, 
			{ "emoji": "????", "name": "Pleading Face" }, 
			{ "emoji": "????", "name": "Crying Face" }, 
			{ "emoji": "????", "name": "Crying Cat Face" }, 
			{ "emoji": "????", "name": "Disappointed Face" }, 
			{ "emoji": "????", "name": "Worried Face" }, 
			{ "emoji": "????", "name": "Slightly Frowning Face" }, 
			{ "emoji": "", "name": "Frowning Face" }, 
			{ "emoji": "????", "name": "Confounded Face" } 
		], 
			"Angry": [ 
				{ "emoji": "????", "name": "Angry Face" }, 
				{ "emoji": "????", "name": "Pouting Face" }, 
				{ "emoji": "????", "name": "Face with Symbols on Mouth" }, 
				{ "emoji": "????", "name": "Face with Steam From Nose" }, 
				{ "emoji": "????", "name": "Expressionless Face" }, 
				{ "emoji": "????", "name": "Unamused Face" }, 
				{ "emoji": "????", "name": "Pouting Cat Face" }, 
				{ "emoji": "????", "name": "Confused Face" }, 
				{ "emoji": "????", "name": "Slightly Frowning Face" }, 
				{ "emoji": "", "name": "Frowning Face" }, 
				{ "emoji": "????", "name": "Confounded Face" }, 
				{ "emoji": "????", "name": "Suffering Face" }, 
				{ "emoji": "????", "name": "Tired Face" }, 
				{ "emoji": "????", "name": "Angry Face" }, 
				{ "emoji": "????", "name": "Pouting Face" }, 
				{ "emoji": "????", "name": "Face with Symbols on Mouth" }, 
				{ "emoji": "????", "name": "Face with Steam From Nose" }, 
				{ "emoji": "????", "name": "Unamused Face" }, 
				{ "emoji": "????", "name": "Pouting Cat Face" }, 
				{ "emoji": "????", "name": "Confused Face" } 
			], 
				"Excited": [ 
					{ "emoji": "????", "name": "Grinning Face with Big Eyes" }, 
					{ "emoji": "????", "name": "Star-Struck" }, 
					{ "emoji": "????", "name": "Smiling Face with Sunglasses" }, 
					{ "emoji": "????", "name": "Partying Face" }, 
					{ "emoji": "????", "name": "Beaming Face with Smiling Eyes" }, 
					{ "emoji": "????", "name": "Grinning Squinting Face" }, 
					{ "emoji": "????", "name": "Zany Face" }, 
					{ "emoji": "????", "name": "Grinning Face" }, 
					{ "emoji": "????", "name": "Smiling Face with Open Mouth and Smiling Eyes" }, 
					{ "emoji": "????", "name": "Face with Tears of Joy" }, 
					{ "emoji": "????", "name": "Rolling on the Floor Laughing" }, 
					{ "emoji": "????", "name": "Grinning Face with Sweat" }, 
					{ "emoji": "????", "name": "Slightly Smiling Face" }, 
					{ "emoji": "????", "name": "Smiling Face with Smiling Eyes" }, 
					{ "emoji": "????", "name": "Smiling Face with Halo" }, 
					{ "emoji": "????", "name": "Smiling Face with Hearts" }, 
					{ "emoji": "????", "name": "Heart Eyes" }, 
					{ "emoji": "????", "name": "Face Blowing a Kiss" }, 
					{ "emoji": "????", "name": "Kissing Face" }, 
					{ "emoji": "????", "name": "Kissing Face with Closed Eyes" } 
				] 
}
